// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: marRSFqQwX6qmgsS5vTWj
// Component: H0T_MehqSnX3S
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: yWLjFzWxUuek1/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_saa_s_website.module.css"; // plasmic-import: marRSFqQwX6qmgsS5vTWj/projectcss
import sty from "./PlasmicBlogPosts.module.css"; // plasmic-import: H0T_MehqSnX3S/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: ki9OdJ413nFLyV/icon
import ArrowRightsvgIcon from "./icons/PlasmicIcon__ArrowRightsvg"; // plasmic-import: 6fEnb6NAgv9orA/icon

export type PlasmicBlogPosts__VariantMembers = {};

export type PlasmicBlogPosts__VariantsArgs = {};
type VariantPropType = keyof PlasmicBlogPosts__VariantsArgs;
export const PlasmicBlogPosts__VariantProps = new Array<VariantPropType>();

export type PlasmicBlogPosts__ArgsType = {};
type ArgPropType = keyof PlasmicBlogPosts__ArgsType;
export const PlasmicBlogPosts__ArgProps = new Array<ArgPropType>();

export type PlasmicBlogPosts__OverridesType = {
  root?: p.Flex<"section">;
  h2?: p.Flex<"h2">;
};

export interface DefaultBlogPostsProps {
  className?: string;
}

function PlasmicBlogPosts__RenderFunc(props: {
  variants: PlasmicBlogPosts__VariantsArgs;
  args: PlasmicBlogPosts__ArgsType;
  overrides: PlasmicBlogPosts__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = Object.assign(
    {},

    props.args
  );
  const $props = args;

  return (
    <section
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.column__nhvQ6)}>
        <h2
          data-plasmic-name={"h2"}
          data-plasmic-override={overrides.h2}
          className={classNames(
            projectcss.all,
            projectcss.h2,
            projectcss.__wab_text,
            sty.h2
          )}
        >
          {"Blog"}
        </h2>

        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__kpPxv
          )}
        >
          {
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. \nLorem Ipsum has been the industry's standard dummy text ever since the 1500s"
          }
        </div>

        <div className={classNames(projectcss.all, sty.columns__p7F4A)}>
          <div className={classNames(projectcss.all, sty.column__ymta8)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__uiFrr)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: "/plasmic/saa_s_website/images/fakurianDesignPPTwRTkvXqUnsplashjpg.jpeg",
                fullWidth: 1920,
                fullHeight: 1280,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__xStbg)}>
              <div className={classNames(projectcss.all, sty.column__umIJk)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lvHq7
                  )}
                >
                  {"January 03, 2021"}
                </div>

                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4__fH441
                  )}
                >
                  {"Convincing reasons you need to learn"}
                </h4>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__vLm2I
                  )}
                >
                  {
                    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ....\n"
                  }
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button__gDgwt)}
                  color={"softBlue" as const}
                  endIcon={
                    <ArrowRightsvgIcon
                      className={classNames(projectcss.all, sty.svg__hfZ71)}
                      role={"img"}
                    />
                  }
                  shape={"rounded" as const}
                  showEndIcon={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cMshx
                    )}
                  >
                    {"READ MORE"}
                  </div>
                </Button>
              </div>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.column___2Ctye)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img___0Oeuw)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"100%" as const}
              loading={"lazy" as const}
              src={{
                src: "/plasmic/saa_s_website/images/fakurianDesignLfbhDph3QYUnsplashjpg.jpeg",
                fullWidth: 1920,
                fullHeight: 1080,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns__yzRFd)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__jecwi)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__rJrZr
                  )}
                >
                  {"January 03, 2021"}
                </div>

                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4___03Gg3
                  )}
                >
                  {"The five devices you need to work anytime"}
                </h4>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hqmNr
                  )}
                >
                  {
                    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ....\n"
                  }
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button__ogLBw)}
                  color={"softBlue" as const}
                  endIcon={
                    <ArrowRightsvgIcon
                      className={classNames(projectcss.all, sty.svg___5ZWd6)}
                      role={"img"}
                    />
                  }
                  shape={"rounded" as const}
                  showEndIcon={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__uRIn
                    )}
                  >
                    {"READ MORE"}
                  </div>
                </Button>
              </p.Stack>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.column__mXap0)}>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__uyrWy)}
              displayHeight={"230px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"100%" as const}
              loading={"lazy" as const}
              src={{
                src: "/plasmic/saa_s_website/images/blog2390X290Jpg.jpeg",
                fullWidth: 390,
                fullHeight: 290,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.columns___5V38K)}>
              <div className={classNames(projectcss.all, sty.column__dJmMh)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__k85V
                  )}
                >
                  {"January 03, 2021"}
                </div>

                <h4
                  className={classNames(
                    projectcss.all,
                    projectcss.h4,
                    projectcss.__wab_text,
                    sty.h4__zsLAl
                  )}
                >
                  {"Tiktok Illegally collecting data sharing"}
                </h4>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tRKo
                  )}
                >
                  {
                    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ....\n"
                  }
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button__mh3G6)}
                  color={"softBlue" as const}
                  endIcon={
                    <ArrowRightsvgIcon
                      className={classNames(projectcss.all, sty.svg__gkZu9)}
                      role={"img"}
                    />
                  }
                  shape={"rounded" as const}
                  showEndIcon={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___30WYi
                    )}
                  >
                    {"READ MORE"}
                  </div>
                </Button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "h2"],
  h2: ["h2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "section";
  h2: "h2";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBlogPosts__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBlogPosts__VariantsArgs;
    args?: PlasmicBlogPosts__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicBlogPosts__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicBlogPosts__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicBlogPosts__ArgProps,
      internalVariantPropNames: PlasmicBlogPosts__VariantProps
    });

    return PlasmicBlogPosts__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBlogPosts";
  } else {
    func.displayName = `PlasmicBlogPosts.${nodeName}`;
  }
  return func;
}

export const PlasmicBlogPosts = Object.assign(
  // Top-level PlasmicBlogPosts renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h2: makeNodeComponent("h2"),

    // Metadata about props expected for PlasmicBlogPosts
    internalVariantProps: PlasmicBlogPosts__VariantProps,
    internalArgProps: PlasmicBlogPosts__ArgProps
  }
);

export default PlasmicBlogPosts;
/* prettier-ignore-end */
